# Generated by Django 5.2.13 on 2026-04-28 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_lotimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_lots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lot',
            name='winner_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='winner_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('winner_assigned', 'Winner assigned'), ('no_bids', 'No bids'), ('reserve_not_met', 'Reserve not met')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='lot',
            name='winning_bid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_lot', to='auctions.bid'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['winner_status', 'winner_calculated_at'], name='lot_winner_status_idx'),
        ),
    ]
