# Generated by Django 5.2.13 on 2026-04-28 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_lot_winner_lot_winner_calculated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending confirmation'), ('winner_confirmed', 'Winner confirmed'), ('seller_contacted', 'Seller contacted'), ('awaiting_collection_or_delivery', 'Awaiting collection or delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending_confirmation', max_length=40)),
                ('confirmation_notes', models.TextField(blank=True)),
                ('seller_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('public_winner_message', models.TextField(blank=True)),
                ('last_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_records', to='auctions.auction')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment', to='auctions.lot')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_records', to=settings.AUTH_USER_MODEL)),
                ('winning_bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_records', to='auctions.bid')),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
                'indexes': [models.Index(fields=['status', '-updated_at'], name='fulfillment_status_idx'), models.Index(fields=['winner', '-updated_at'], name='fulfillment_winner_idx'), models.Index(fields=['auction', 'status'], name='fulfillment_auction_status_idx')],
            },
        ),
    ]
