# Generated by Django 5.2.13 on 2026-04-28 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_fulfillmentrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeRepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_outcome', models.CharField(choices=[('pending', 'Pending'), ('winner_assigned', 'Winner assigned'), ('no_bids', 'No bids'), ('reserve_not_met', 'Reserve not met')], max_length=30)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='pending_review', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outcome_repairs_applied', to=settings.AUTH_USER_MODEL)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcome_repair_requests', to='auctions.auction')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcome_repair_requests', to='auctions.lot')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcome_repairs_requested', to=settings.AUTH_USER_MODEL)),
                ('requested_winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_outcome_repairs_as_winner', to=settings.AUTH_USER_MODEL)),
                ('requested_winning_bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_outcome_repairs', to='auctions.bid')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outcome_repairs_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['status', '-created_at'], name='repair_status_created_idx'), models.Index(fields=['lot', 'status'], name='repair_lot_status_idx')],
            },
        ),
    ]
