# Generated by Codex on 2026-05-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_outcomerepairrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="outcomerepairrequest",
            name="approval_notes",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="OutcomeRepairComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment_text", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outcome_repair_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "repair_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="auctions.outcomerepairrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "indexes": [
                    models.Index(fields=["repair_request", "created_at"], name="repair_comment_time_idx"),
                ],
            },
        ),
    ]
