# Generated by Django 5.2.14 on 2026-05-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_outcomerepairrequest_approval_notes_and_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('AUCTION_NOT_LIVE', 'Auction is not live'), ('AUCTION_NOT_STARTED', 'Auction has not started'), ('AUCTION_ENDED', 'Auction has ended'), ('LOT_CLOSED', 'Lot is closed'), ('BID_TOO_LOW', 'Bid is too low'), ('INVALID_INCREMENT', 'Bid increment is invalid'), ('USER_NOT_ALLOWED', 'User is not allowed to bid'), ('UNAUTHENTICATED', 'User is not authenticated'), ('RATE_LIMITED', 'Bidder is rate limited'), ('SERVER_ERROR', 'Server error')], max_length=40, null=True),
        ),
    ]
