# Generated by Django 5.2.13 on 2026-04-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_registered', 'User registered'), ('auction_created', 'Auction created'), ('auction_updated', 'Auction updated'), ('auction_ended', 'Auction ended'), ('auction_close_run', 'Auction close run'), ('lot_created', 'Lot created'), ('lot_updated', 'Lot updated'), ('bid_accepted', 'Bid accepted'), ('bid_rejected', 'Bid rejected'), ('bid_anomaly_detected', 'Bid anomaly detected'), ('winner_calculated', 'Winner calculated'), ('alert_triggered', 'Alert triggered'), ('notification_event', 'Notification event'), ('job_failed', 'Job failed'), ('admin_action', 'Admin action')], max_length=60),
        ),
    ]
