# Generated by Django 5.2.13 on 2026-04-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_registered', 'User registered'), ('auction_created', 'Auction created'), ('auction_updated', 'Auction updated'), ('auction_ended', 'Auction ended'), ('auction_close_run', 'Auction close run'), ('lot_created', 'Lot created'), ('lot_updated', 'Lot updated'), ('bid_accepted', 'Bid accepted'), ('bid_rejected', 'Bid rejected'), ('bid_anomaly_detected', 'Bid anomaly detected'), ('winner_calculated', 'Winner calculated'), ('winner_outcome_backfilled', 'Winner outcome backfilled'), ('alert_triggered', 'Alert triggered'), ('notification_event', 'Notification event'), ('job_failed', 'Job failed'), ('fulfillment_created', 'Fulfillment created'), ('fulfillment_status_changed', 'Fulfillment status changed'), ('fulfillment_invalid_transition', 'Fulfillment invalid transition'), ('fulfillment_confirmation_notes_updated', 'Fulfillment confirmation notes updated'), ('fulfillment_seller_notes_updated', 'Fulfillment seller notes updated'), ('fulfillment_admin_notes_updated', 'Fulfillment admin notes updated'), ('fulfillment_completed', 'Fulfillment completed'), ('fulfillment_cancelled', 'Fulfillment cancelled'), ('fulfillment_disputed', 'Fulfillment disputed'), ('admin_action', 'Admin action')], max_length=60),
        ),
    ]
