# Generated by Codex on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0008_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                max_length=60,
                choices=[
                    ("user_registered", "User registered"),
                    ("auction_created", "Auction created"),
                    ("auction_updated", "Auction updated"),
                    ("auction_ended", "Auction ended"),
                    ("auction_close_run", "Auction close run"),
                    ("lot_created", "Lot created"),
                    ("lot_updated", "Lot updated"),
                    ("bid_accepted", "Bid accepted"),
                    ("bid_rejected", "Bid rejected"),
                    ("bid_anomaly_detected", "Bid anomaly detected"),
                    ("winner_calculated", "Winner calculated"),
                    ("winner_outcome_backfilled", "Winner outcome backfilled"),
                    ("outcome_repair_requested", "Outcome repair requested"),
                    ("outcome_repair_approved", "Outcome repair approved"),
                    ("outcome_repair_invalid_approval", "Outcome repair invalid approval"),
                    ("outcome_repair_rejected", "Outcome repair rejected"),
                    ("outcome_repair_applied", "Outcome repair applied"),
                    ("outcome_repair_cancelled", "Outcome repair cancelled"),
                    ("outcome_repair_comment_created", "Outcome repair comment created"),
                    ("outcome_repair_audit_viewed", "Outcome repair audit viewed"),
                    ("admin_activity_exported", "Admin activity exported"),
                    ("deployment_check_run", "Deployment check run"),
                    ("staging_seed_run", "Staging seed run"),
                    ("backup_verification_run", "Backup verification run"),
                    ("release_check_run", "Release check run"),
                    ("alert_triggered", "Alert triggered"),
                    ("notification_event", "Notification event"),
                    ("notification_marked_read", "Notification marked read"),
                    ("notifications_marked_read", "Notifications marked read"),
                    ("job_failed", "Job failed"),
                    ("fulfillment_created", "Fulfillment created"),
                    ("fulfillment_status_changed", "Fulfillment status changed"),
                    ("fulfillment_invalid_transition", "Fulfillment invalid transition"),
                    ("fulfillment_confirmation_notes_updated", "Fulfillment confirmation notes updated"),
                    ("fulfillment_seller_notes_updated", "Fulfillment seller notes updated"),
                    ("fulfillment_admin_notes_updated", "Fulfillment admin notes updated"),
                    ("fulfillment_completed", "Fulfillment completed"),
                    ("fulfillment_cancelled", "Fulfillment cancelled"),
                    ("fulfillment_disputed", "Fulfillment disputed"),
                    ("admin_action", "Admin action"),
                ],
            ),
        ),
    ]
