# Generated by Django 5.2.14 on 2026-06-07 23:54

import apps.raffles.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0009_alter_bid_rejection_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('draw_time', models.DateTimeField()),
                ('max_tickets', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('closed', 'Closed'), ('drawn', 'Drawn'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raffle_campaigns', to='auctions.auction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_raffle_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_time', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='RaffleDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawn_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('randomness_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='draw', to='raffles.rafflecampaign')),
                ('drawn_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raffle_draws_executed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-drawn_at', '-id'),
            },
            bases=(apps.raffles.models.ImmutableAfterCreateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RafflePrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to=apps.raffles.models.raffle_prize_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp', 'gif'))])),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='raffles.rafflecampaign')),
            ],
            options={
                'ordering': ('campaign', 'position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RafflePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('charity_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_reference', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raffle_purchases', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='raffles.rafflecampaign')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RaffleTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.PositiveIntegerField()),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('void', 'Void')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='raffles.rafflecampaign')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raffle_tickets', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='raffles.rafflepurchase')),
            ],
            options={
                'ordering': ('campaign', 'ticket_number', 'id'),
            },
            bases=(apps.raffles.models.ImmutableAfterCreateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RaffleWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winners', to='raffles.rafflecampaign')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winners', to='raffles.raffleprize')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='winner_record', to='raffles.raffleticket')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raffle_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('campaign', 'prize__position', 'id'),
            },
            bases=(apps.raffles.models.ImmutableAfterCreateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SellerRaffleFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(choices=[('essentials', 'Essentials'), ('signature', 'Signature'), ('custom', 'Custom')], default='essentials', max_length=30)),
                ('raffles_enabled', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_feature', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('seller_id',),
            },
        ),
        migrations.AddIndex(
            model_name='rafflecampaign',
            index=models.Index(fields=['status', 'start_time', 'end_time'], name='raffle_campaign_time_idx'),
        ),
        migrations.AddIndex(
            model_name='rafflecampaign',
            index=models.Index(fields=['auction', 'status'], name='raffle_campaign_auction_idx'),
        ),
        migrations.AddIndex(
            model_name='rafflecampaign',
            index=models.Index(fields=['created_by', 'status'], name='raffle_campaign_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='rafflecampaign',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='raffle_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='rafflecampaign',
            constraint=models.CheckConstraint(condition=models.Q(('draw_time__gte', models.F('end_time'))), name='raffle_draw_after_end'),
        ),
        migrations.AddConstraint(
            model_name='rafflecampaign',
            constraint=models.CheckConstraint(condition=models.Q(('max_tickets__gt', 0)), name='raffle_max_tickets_positive'),
        ),
        migrations.AddIndex(
            model_name='raffledraw',
            index=models.Index(fields=['drawn_by', '-drawn_at'], name='raffle_draw_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='raffleprize',
            index=models.Index(fields=['campaign', 'position'], name='raffle_prize_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='raffleprize',
            constraint=models.UniqueConstraint(fields=('campaign', 'position'), name='raffle_prize_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='raffleprize',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='raffle_prize_position_positive'),
        ),
        migrations.AddIndex(
            model_name='rafflepurchase',
            index=models.Index(fields=['campaign', 'status'], name='raffle_purchase_campaign_idx'),
        ),
        migrations.AddIndex(
            model_name='rafflepurchase',
            index=models.Index(fields=['buyer', '-created_at'], name='raffle_purchase_buyer_idx'),
        ),
        migrations.AddConstraint(
            model_name='rafflepurchase',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='raffle_purchase_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='rafflepurchase',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gte', 0)), name='raffle_purchase_gross_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='rafflepurchase',
            constraint=models.CheckConstraint(condition=models.Q(('platform_fee_amount__gte', 0)), name='raffle_purchase_fee_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='rafflepurchase',
            constraint=models.CheckConstraint(condition=models.Q(('charity_amount__gte', 0)), name='raffle_purchase_charity_nonneg'),
        ),
        migrations.AddIndex(
            model_name='raffleticket',
            index=models.Index(fields=['owner', '-issued_at'], name='raffle_ticket_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='raffleticket',
            index=models.Index(fields=['campaign', 'status'], name='raffle_ticket_campaign_idx'),
        ),
        migrations.AddConstraint(
            model_name='raffleticket',
            constraint=models.UniqueConstraint(fields=('campaign', 'ticket_number'), name='raffle_ticket_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='raffleticket',
            constraint=models.CheckConstraint(condition=models.Q(('ticket_number__gt', 0)), name='raffle_ticket_number_positive'),
        ),
        migrations.AddIndex(
            model_name='rafflewinner',
            index=models.Index(fields=['winner', '-created_at'], name='raffle_winner_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='rafflewinner',
            constraint=models.UniqueConstraint(fields=('campaign', 'prize'), name='raffle_winner_prize_unique'),
        ),
        migrations.AddIndex(
            model_name='sellerrafflefeature',
            index=models.Index(fields=['plan_code', 'raffles_enabled'], name='raffle_feature_plan_idx'),
        ),
    ]
