# Generated by Django for BIDALS lead capture.

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeadRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("organisation", models.CharField(max_length=160)),
                (
                    "fundraising_focus",
                    models.CharField(
                        choices=[
                            ("auctions", "Auctions"),
                            ("raffles", "Raffles"),
                            ("donations", "Donations"),
                            ("multi_channel", "Multi-channel event"),
                            ("general_enquiry", "General enquiry"),
                            ("partnership", "Partnership"),
                            ("support", "Support"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("message", models.TextField(validators=(django.core.validators.MaxLengthValidator(2000),))),
                (
                    "source_page",
                    models.CharField(
                        choices=[("book_demo", "Book demo"), ("contact", "Contact")],
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewed", "Reviewed"),
                            ("contacted", "Contacted"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="lead_status_created_idx"),
                    models.Index(fields=["source_page", "-created_at"], name="lead_source_created_idx"),
                    models.Index(fields=["email", "-created_at"], name="lead_email_created_idx"),
                ],
            },
        ),
    ]
